language: python

matrix:
  include:
    - dist: xenial
      services: docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip

env:
  global:
    - CIBW_SKIP=*-manylinux1_i686 cp27-* cp35-* cp36-*

script:
  - make test
  - $PIP install cibuildwheel==0.10.2
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
